productapi:
  host: "productapi"
  port: 8080
  readtimeout: 10ms
  writetimeout: 600ms
  jwt_sercet: "duong"
  use_jwt: true

currency:
  host: "currency"
  port: 9092

psql:
  host: "psql"
  port: 5432
  username: postgres
  password: postgres
  dbname: product
  querytimeout: 1s
  healthcheck_interval: 20s
