version: "3.8"

services:
  currency:
    image: "duongtomho/currencygrpc:latest"
    restart: always
    ports:
      - "9092"
    volumes:
      - ../currency/:/app

  product:
    image: "duongtomho/productapi:latest"
    restart: always
    depends_on:
      - currency
    ports:
      - "8080:8080"
    environment:
      SEVERVER_HOST: productapi
      SEVERVER_PORT: 9090
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - ../product-api/:/app
