version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: products
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  currency:
    image: "duongtomho/currencygrpc:latest"
    restart: always
    ports:
      - "9092"
    volumes:
      - ../currency/:/app

  product:
    image: "duongtomho/productapi:latest"
    restart: always
    depends_on:
      - currency
    ports:
      - "8080:8080"
    environment:
      SEVERVER_HOST: productapi
      SEVERVER_PORT: 9090
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - ../product-api/:/app
