version: "3.8"

services:
  psql:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product
    volumes:
      - ../product-api/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: users
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  auth:
    image: "duongtomho/auth-service"
    restart: always
    depends_on:
      - mongo
    ports:
      - "8082:8082"
    volumes:
      - ../auth-service/:/app

  currency:
    image: "duongtomho/currencygrpc:latest"
    restart: always
    ports:
      - "9092"
    volumes:
      - ../currency/:/app

  product:
    image: "duongtomho/productapi:latest"
    restart: always
    depends_on:
      - psql
      - currency
      - auth
    ports:
      - "8080:8080"
    environment:
      SEVERVER_HOST: productapi
      SEVERVER_PORT: 9090
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    volumes:
      - ../product-api/:/app
