authservice:
  host: "authservice"
  port: 8082
  readtimeout: 10ms
  writetimeout: 600ms
  jwt_sercet: "duong"
  db_collection: authinfo

mongodb:
  host: "mongo"
  port: 27017
  username: admin
  password: admin
  dbname: users
  querytimeout: 5s
  healthcheck_interval: 5s
